# Generated by Django 4.2.7 on 2024-08-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
